spring:

  datasource:
    username: root
    password: lhp,,123
    url: jdbc:mysql://1.15.112.44:3306/my_project?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8
#    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 2446268838@qq.com
    nickname: 数据交换平台
    password: zuugchwmpcjjeafe
    default-encoding:  UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true #调试模式
    test-connection: true #启动项目时验证是否可以正确通信 默认为false







datax:
  pypath: F:\SoftFile\datax\datax\bin/datax.py


